# Part 4: Numpy Tools

In [65]:
import numpy as np

## 4.1 Random Sampling (np.random)

In [66]:
import numpy.random as rnd

```rnd.random((n,m))```

This gives us a uniform random distribution between $0\rightarrow 1$, of shape $(n,m)$

In [67]:
rarr = rnd.random((3,2))

print(rarr,'\n')
print(100*rarr,'\n')

[[0.91773308 0.39642544]
 [0.2464477  0.82442703]
 [0.30713893 0.94217487]] 

[[91.77330755 39.64254414]
 [24.64476998 82.44270303]
 [30.71389312 94.21748668]] 



```rnd.normal(mu,sig,size)```

This gives us a normal distribution with mean $mu$ and standard deviation $sig$, of length $size$.

In [68]:
mu, sig, size = 100,10,10

norm_arr = rnd.normal(mu,sig,size)

print(norm_arr,'\n')

[100.86123576  93.26741647 129.58883078 101.16224037  99.99830871
  82.58708135  99.76226034 111.96403037  99.59665429 100.95697965] 



```rnd.choice(array,size)```

This randomly chooses elements from this $array$, with length $size$.

In [93]:
arr = np.arange(10)
print(arr,'\n')

size = 100

choo = rnd.choice(arr,size)
print(choo)

[0 1 2 3 4 5 6 7 8 9] 

[8 7 8 1 1 3 8 7 7 3 6 7 5 2 3 1 3 7 4 4 7 6 3 6 5 7 5 1 5 3 5 3 4 2 0 4 8
 0 4 3 1 3 2 4 2 8 8 9 9 0 9 2 4 2 0 1 7 5 5 6 1 5 6 3 8 7 1 2 9 0 3 4 0 1
 3 3 4 8 1 9 4 3 2 4 5 5 0 9 3 1 4 7 2 5 4 6 6 3 4 6]


## 4.1 Binary Operations

We can perform binary operations on Numpy arrays.

### 4.1.1 Bitwise Operations

In [70]:
a = np.array([5,6,7,8]) # [0101, 0110, 0111,1000]
b = np.array([12,13,14,15]) #[1100, 1101, 1110, 1111]

```np.bitwise_and(array1,array2)```
The bitwise-and operation:

In [71]:
print(np.bitwise_and(a,b)) #[0100, 0100, 0110,1000]

[4 4 6 8]


```np.bitwise_or(array1,array2)```
The bitwise-or operation:

In [72]:
print(np.bitwise_or(a,b)) #[1101,1111,1111,1111]

[13 15 15 15]


```np.bitwise_xor(array1,array2)```
The bitwise-xor operation:

In [73]:
print(np.bitwise_xor(a,b)) #[1001,1011,1001,0111]

[ 9 11  9  7]


```np.invert(array)```
The bitwise-inversion operation:

In [74]:
print(np.invert(a)) #[-(0101+0001)=-0110, -0111, -1000, -1001]

[-6 -7 -8 -9]


### 4.1.2 Shift Operations

In [75]:
a = np.array([5,6,7,8]) # [0101, 0110, 0111,1000]

```np.left_shift(array,step)```
Shifts the binary representation of the number $step$ to the left.

In [76]:
print(np.left_shift(a,1)) #[1010 = 10, 1100=12, 1110=14, 10000=16]
print(np.left_shift(a,2)) #[10100 = 20, 11000=24, 11100=28, 100000=32]

[10 12 14 16]
[20 24 28 32]


```np.right_shift(array,step)```
Shifts the binary representation of the number $step$ to the right.

In [77]:
print(np.right_shift(a,1)) #[0010 = 2, 0011=3, 0011=3, 0100=4]
print(np.right_shift(a,2)) #[0001 = 1, 0001=1, 0001=1, 0010=2]

[2 3 3 4]
[1 1 1 2]


## 4.2 Polynomials

A polynomial is an expression with different variables and coefficients, they are encapsulated in the form

$$p(x,n) = c[0]x^n + c[2]x^{n-1} +...+ c[n-1]x ^1 + c[n]x^0 $$

where $c[i]$ is the i-th coefficient.

In Numpy we can perform many operations with polynomials.

```np.polyval(c,x) ```

We can evaluate a polynomial for $p(x,n)$, given a list of coefficients $c$ and $x$.

For example,

$$ 1x^2+4x^1 -2x^0 $$
or
$$ x^2+4x-2$$

$$x=2$$

$$ \implies 2^2 + 4\times 2 -2 = 10$$

In [86]:
c = [1,4,-2]
x = 2

print('p = ',np.polyval(c,x))

p =  10


```np.roots(c) ```

We can also find the roots of a polynomial, given $c$.

In [92]:
c = [1,4,4]

print('x = ',np.roots(c))

x =  [-2. -2.]


```np.polyfit(x,y,n) ```

We can also fit data points, (x,y), to some polynomial with a highest power of $x^n$. This serves as a usual approximation for data.

In [102]:
x = 10*rnd.random(10)
y = 10*rnd.random(10)

poly = np.polyfit(x,y,2) # poly[0]x^2 + poly[1]x^1 + poly[2]x^0 = y 
print('poly = ',poly, '\n') 

print('c[0] = ', poly[0])
print('c[1] = ', poly[1])
print('c[2] = ', poly[2])

poly =  [-0.16970111  1.8799587   1.97326199] 

c[0] =  -0.16970111190569737
c[1] =  1.8799587039006747
c[2] =  1.9732619914236167


## 4.3 Data Analysis

We can calculate the mean, standard deviation, variation, min, max, sum and product of arrays.

In [158]:
data = 100*rnd.random((1000,2))
print(data)

[[95.25878707 82.72808741]
 [35.76745147  0.38491428]
 [83.18509211 41.83954657]
 ...
 [72.36033186  8.52177699]
 [73.00956157 58.69690757]
 [88.72411099 56.14476627]]


```np.mean(array)```

This finds the average/mean of some data.

In [202]:
print(np.mean(data))

20.555555555555557


```np.std(array)```

The standard deviation.

In [203]:
print(np.std(data))

29.0788625450443


```np.var(array)```

The variance.

In [204]:
print(np.var(data))

845.5802469135803


```np.min(array)```

The minimum.

In [205]:
print(data.min())

1


```np.max(array)```

The maximum.

In [206]:
print(data.max())

100


```sum(array)```

The sum.

In [207]:
data = np.arange(1,10)
print(data)

[1 2 3 4 5 6 7 8 9]


In [208]:
print(sum(data))

45


```np.prod(array)```

The product.

In [209]:
print(np.prod(data[0:4])) #1x2x3x4=24

24


```np.cumsum(array)```

The cumulative sum.

In [210]:
print(np.cumsum(data))

[ 1  3  6 10 15 21 28 36 45]


```np.cumprod(array)```

The cumulative product.

In [211]:
print(np.cumprod(data))

[     1      2      6     24    120    720   5040  40320 362880]


```np.trace(array)```

The trace of the array/matrix.(The sum along the diagonal.)

In [212]:
data1 = [1,5,10]
data2 = [13,4,27]
data3 = [7,18,100]


data = np.array([data1,data2,data3])
print(data)

[[  1   5  10]
 [ 13   4  27]
 [  7  18 100]]


In [213]:
print(np.trace(data))

105


## 4.5 I/O

We can use $np.loadtxt()$ and $np.savetxt()$ to read in and save files. Recall [2.3 Inputs & Files](../PyQm_Week2/PyQM_2.3_Inputs_Files.ipynb) and the related exercises involving the normalisation of quibits.

In [215]:
print(np.loadtxt("quibits.txt"))

[[2.3000e+01 2.5000e+01]
 [6.7000e+01 3.8470e+03]
 [2.3600e+02 8.7420e+03]
 [5.6000e+01 8.4300e+02]
 [4.6720e+03 7.8000e+01]
 [3.6200e+02 9.2490e+03]
 [4.6730e+03 4.3000e+01]
 [4.8210e+03 7.4890e+03]
 [2.3300e+02 2.9348e+04]
 [3.7200e+02 4.8900e+02]]


In [216]:
q_col1 = np.loadtxt("quibits.txt", delimiter = ' ', usecols= 0)
q_col2 = np.loadtxt("quibits.txt", delimiter = ' ', usecols= 1)

print(q_col1, '\n')
print(q_col2, '\n')

[  23.   67.  236.   56. 4672.  362. 4673. 4821.  233.  372.] 

[2.5000e+01 3.8470e+03 8.7420e+03 8.4300e+02 7.8000e+01 9.2490e+03
 4.3000e+01 7.4890e+03 2.9348e+04 4.8900e+02] 



In [217]:
#Normalise
q_col1, q_col2 = q_col1/(np.sqrt(q_col1**2+q_col2**2)), q_col2/(np.sqrt(q_col1**2+q_col2**2))

print(q_col1, '\n')
print(q_col2, '\n')

print(q_col1**2 + q_col2**2)

np.savetxt("normalised_quibits.txt", list(zip(q_col1,q_col2)))

[0.67705653 0.01741353 0.02698628 0.06628333 0.99986066 0.03910942
 0.99995767 0.54128523 0.00793896 0.6054546 ] 

[0.73593101 0.99984837 0.9996358  0.99780084 0.01669288 0.99923493
 0.00920141 0.84083905 0.99996849 0.79587984] 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [218]:
print(np.loadtxt("normalised_quibits.txt", delimiter = ' '))

[[0.67705653 0.73593101]
 [0.01741353 0.99984837]
 [0.02698628 0.9996358 ]
 [0.06628333 0.99780084]
 [0.99986066 0.01669288]
 [0.03910942 0.99923493]
 [0.99995767 0.00920141]
 [0.54128523 0.84083905]
 [0.00793896 0.99996849]
 [0.6054546  0.79587984]]
