# Part 4: Numpy Tools

In [1]:
import numpy as np

## 4.1 Random Sampling (np.random)

In [2]:
import numpy.random as rnd

```rnd.random((n,m))```

This gives us a uniform random distribution between $0\rightarrow 1$, of shape $(n,m)$

In [3]:
rarr = rnd.random((3,2))

print(rarr,'\n')
print(100*rarr,'\n')

[[0.41483896 0.41698146]
 [0.49009931 0.34963228]
 [0.40401129 0.9140403 ]] 

[[41.48389553 41.69814636]
 [49.00993069 34.96322845]
 [40.40112891 91.40403027]] 



```rnd.normal(mu,sig,size)```

This gives us a normal distribution with mean $mu$ and standard deviation $sig$, of length $size$.

In [4]:
mu, sig, size = 100,10,10

norm_arr = rnd.normal(mu,sig,size)

print(norm_arr,'\n')

[ 91.48191223  97.19147068 107.77558701  93.51075252 119.8930174
  94.31891835 110.52648516  88.92543853  89.34028857  94.93128317] 



```rnd.choice(array,size)```

This randomly chooses elements from this $array$, with length $size$.

In [5]:
arr = np.arange(10)
print(arr,'\n')

size = 100

choo = rnd.choice(arr,size)
print(choo)

[0 1 2 3 4 5 6 7 8 9] 

[7 5 3 2 2 1 6 9 0 1 8 9 2 0 5 4 8 5 2 6 6 8 2 8 5 6 2 7 2 8 0 3 4 8 1 0 2
 5 1 9 4 6 5 9 1 3 8 2 8 0 2 8 0 6 4 4 7 4 3 5 6 1 8 8 4 2 2 2 8 8 0 0 9 7
 6 3 7 6 9 5 8 4 1 5 2 8 3 3 4 7 9 4 1 3 9 5 9 1 0 4]


## 4.1 Binary Operations

We can perform binary operations on Numpy arrays.

### 4.1.1 Bitwise Operations

In [6]:
a = np.array([5,6,7,8]) # [0101, 0110, 0111,1000]
b = np.array([12,13,14,15]) #[1100, 1101, 1110, 1111]

```np.bitwise_and(array1,array2)```
The bitwise-and operation:

In [7]:
print(np.bitwise_and(a,b)) #[0100, 0100, 0110,1000]

[4 4 6 8]


```np.bitwise_or(array1,array2)```
The bitwise-or operation:

In [8]:
print(np.bitwise_or(a,b)) #[1101,1111,1111,1111]

[13 15 15 15]


```np.bitwise_xor(array1,array2)```
The bitwise-xor operation:

In [9]:
print(np.bitwise_xor(a,b)) #[1001,1011,1001,0111]

[ 9 11  9  7]


```np.invert(array)```
The bitwise-inversion operation:

In [10]:
print(np.invert(a)) #[-(0101+0001)=-0110, -0111, -1000, -1001]

[-6 -7 -8 -9]


### 4.1.2 Shift Operations

In [11]:
a = np.array([5,6,7,8]) # [0101, 0110, 0111,1000]

```np.left_shift(array,step)```
Shifts the binary representation of the number $step$ to the left.

In [12]:
print(np.left_shift(a,1)) #[1010 = 10, 1100=12, 1110=14, 10000=16]
print(np.left_shift(a,2)) #[10100 = 20, 11000=24, 11100=28, 100000=32]

[10 12 14 16]
[20 24 28 32]


```np.right_shift(array,step)```
Shifts the binary representation of the number $step$ to the right.

In [13]:
print(np.right_shift(a,1)) #[0010 = 2, 0011=3, 0011=3, 0100=4]
print(np.right_shift(a,2)) #[0001 = 1, 0001=1, 0001=1, 0010=2]

[2 3 3 4]
[1 1 1 2]


## 4.2 Polynomials

A polynomial is an expression with different variables and coefficients, they are encapsulated in the form

$$p(x,n) = c[0]x^n + c[2]x^{n-1} +...+ c[n-1]x ^1 + c[n]x^0 $$

where $c[i]$ is the i-th coefficient.

In Numpy we can perform many operations with polynomials.

```np.polyval(c,x) ```

We can evaluate a polynomial for $p(x,n)$, given a list of coefficients $c$ and $x$.

For example,

$$ 1x^2+4x^1 -2x^0 $$
or
$$ x^2+4x-2$$

$$x=2$$

$$ \implies 2^2 + 4\times 2 -2 = 10$$

In [14]:
c = [1,4,-2]
x = 2

print('p = ',np.polyval(c,x))

p =  10


```np.roots(c) ```

We can also find the roots of a polynomial, given $c$.

In [15]:
c = [1,4,4]

print('x = ',np.roots(c))

x =  [-2. -2.]


```np.polyfit(x,y,n) ```

We can also fit data points, (x,y), to some polynomial with a highest power of $x^n$. This serves as a usual approximation for data.

In [16]:
x = 10*rnd.random(10)
y = 10*rnd.random(10)

poly = np.polyfit(x,y,2) # poly[0]x^2 + poly[1]x^1 + poly[2]x^0 = y 
print('poly = ',poly, '\n') 

print('c[0] = ', poly[0])
print('c[1] = ', poly[1])
print('c[2] = ', poly[2])

poly =  [ 0.25707162 -3.05500837 11.92158433] 

c[0] =  0.25707162270905337
c[1] =  -3.055008367909654
c[2] =  11.92158432994597


## 4.3 Data Analysis

We can calculate the mean, standard deviation, variation, min, max, sum and product of arrays.

In [17]:
data = 100*rnd.random((1000,2))
print(data)

[[68.97522256 78.83680082]
 [58.95940855 93.2995051 ]
 [36.67993071 70.2728985 ]
 ...
 [33.72878038  0.73546521]
 [40.9913903  91.4180338 ]
 [28.60250875 94.45787152]]


```np.mean(array)```

This finds the average/mean of some data.

In [18]:
print(np.mean(data))

50.579581583671626


```np.std(array)```

The standard deviation.

In [19]:
print(np.std(data))

28.56298511577721


```np.var(array)```

The variance.

In [20]:
print(np.var(data))

815.8441187241103


```np.min(array)```

The minimum.

In [21]:
print(data.min())

0.14608860177505179


```np.max(array)```

The maximum.

In [22]:
print(data.max())

99.95570066996676


```sum(array)```

The sum.

In [23]:
data = np.arange(1,10)
print(data)

[1 2 3 4 5 6 7 8 9]


In [24]:
print(sum(data))

45


```np.prod(array)```

The product.

In [25]:
print(np.prod(data[0:4])) #1x2x3x4=24

24


```np.cumsum(array)```

The cumulative sum.

In [26]:
print(np.cumsum(data))

[ 1  3  6 10 15 21 28 36 45]


```np.cumprod(array)```

The cumulative product.

In [27]:
print(np.cumprod(data))

[     1      2      6     24    120    720   5040  40320 362880]


```np.trace(array)```

The trace of the array/matrix.(The sum along the diagonal.)

In [28]:
data1 = [1,5,10]
data2 = [13,4,27]
data3 = [7,18,100]


data = np.array([data1,data2,data3])
print(data)

[[  1   5  10]
 [ 13   4  27]
 [  7  18 100]]


In [29]:
print(np.trace(data))

105


## 4.5 I/O

We can use $np.loadtxt()$ and $np.savetxt()$ to read in and save files. Recall [2.3 Inputs & Files](../PyQm_Week2/PyQM_2.3_Inputs_Files.ipynb) and the related exercises involving the normalisation of quibits.

In [30]:
print(np.loadtxt("quibits.txt"))

FileNotFoundError: quibits.txt not found.

In [216]:
q_col1 = np.loadtxt("quibits.txt", delimiter = ' ', usecols= 0)
q_col2 = np.loadtxt("quibits.txt", delimiter = ' ', usecols= 1)

print(q_col1, '\n')
print(q_col2, '\n')

[  23.   67.  236.   56. 4672.  362. 4673. 4821.  233.  372.] 

[2.5000e+01 3.8470e+03 8.7420e+03 8.4300e+02 7.8000e+01 9.2490e+03
 4.3000e+01 7.4890e+03 2.9348e+04 4.8900e+02] 



In [217]:
#Normalise
q_col1, q_col2 = q_col1/(np.sqrt(q_col1**2+q_col2**2)), q_col2/(np.sqrt(q_col1**2+q_col2**2))

print(q_col1, '\n')
print(q_col2, '\n')

print(q_col1**2 + q_col2**2)

np.savetxt("normalised_quibits.txt", list(zip(q_col1,q_col2)))

[0.67705653 0.01741353 0.02698628 0.06628333 0.99986066 0.03910942
 0.99995767 0.54128523 0.00793896 0.6054546 ] 

[0.73593101 0.99984837 0.9996358  0.99780084 0.01669288 0.99923493
 0.00920141 0.84083905 0.99996849 0.79587984] 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [218]:
print(np.loadtxt("normalised_quibits.txt", delimiter = ' '))

[[0.67705653 0.73593101]
 [0.01741353 0.99984837]
 [0.02698628 0.9996358 ]
 [0.06628333 0.99780084]
 [0.99986066 0.01669288]
 [0.03910942 0.99923493]
 [0.99995767 0.00920141]
 [0.54128523 0.84083905]
 [0.00793896 0.99996849]
 [0.6054546  0.79587984]]
